In [8]:
import numpy as np

In [15]:
i=[range(4), range(10,14)]

In [16]:
np.array(i)

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [23]:
a=[(1,2,3,4)(10,11,12,13)]


TypeError: 'tuple' object is not callable

In [26]:
o=np.arange(1,9).reshape(2,9)
print(o)

ValueError: cannot reshape array of size 8 into shape (2,9)

In [38]:
np.linspace(0,2,10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [43]:
In[120]: arr[[4, 3, 0, 6]]


NameError: name 'arr' is not defined

In [44]:
arr = np.array([7,8,3,5,4,2])

In [45]:
arr

array([7, 8, 3, 5, 4, 2])

In [46]:
arr

array([7, 8, 3, 5, 4, 2])

In [47]:
arr%2==0

array([False,  True, False, False,  True,  True])

In [48]:
arr[arr%2==0]

array([8, 4, 2])

In [49]:
arr[arr<5]

array([3, 4, 2])

In [50]:
arr[arr>5]

array([7, 8])

In [51]:
names = ['ahsan' , 'ali' , 'umer' , 'bilal']

In [52]:
type(names)

list

In [53]:
names = np.array(names)

In [55]:
names

array(['ahsan', 'ali', 'umer', 'bilal'], dtype='<U5')

In [73]:
names[np.char.startswith(names, 'a')]

array(['ahsan', 'ali'], dtype='<U5')

In [74]:
names[np.char.startswith(names, 'u')]

array(['umer'], dtype='<U5')

In [75]:
names[np.char.startswith(names, 'b')]

array(['bilal'], dtype='<U5')

In [76]:
names[np.char.startswith(names, 'ah')]a

array(['ahsan'], dtype='<U5')

In [78]:
rand1 = np.random.randn(2,2)

In [79]:
rand1

array([[-1.84619981, -0.61176523],
       [ 1.41118579, -0.68210622]])

In [92]:
rand1**4

array([[11.61755693,  0.14006808],
       [ 3.96585446,  0.21647515]])

In [95]:
a=rand1.astype("complex")

In [96]:
a

array([[-1.84619981+0.j, -0.61176523+0.j],
       [ 1.41118579+0.j, -0.68210622+0.j]])

In [97]:
np.sqrt(a)

array([[0.        +1.35874936j, 0.        +0.78215423j],
       [1.18793341+0.j        , 0.        +0.82589722j]])

In [98]:
rand1


array([[-1.84619981, -0.61176523],
       [ 1.41118579, -0.68210622]])

In [99]:
np.where(rand1<0 ,0, rs

array([[0.        , 0.        ],
       [1.41118579, 0.        ]])

In [104]:
salary = [8989, 98977, -54567, 96000, -78600]
salary = np.array(salary)

In [105]:
np.where(salary<0 ,25000,salary)


array([ 8989, 98977, 25000, 96000, 25000])

In [107]:
np.where(salary<0 ,salary.mean(),salary)


array([ 8989. , 98977. , 14159.8, 96000. , 14159.8])